environments:
  scratch:
  staging:
  production:
---
repositories:
  - name: grafana 
    url: https://grafana.github.io/helm-charts
  - name: aws-ebs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  - name: prometheus-community 
    url: https://prometheus-community.github.io/helm-charts
  - name: stakater
    url: https://stakater.github.io/stakater-charts

releases:

  - name: notify-admin
    namespace: notification-canada-ca
    labels:
      app: notify
      tier: frontend
      category: notification
    chart: stakater/application
    version: 2.2.5
    values:
    - ./overrides/notify/admin.yaml.gotmpl

  - name: aws-ebs-csi-driver
    namespace: kube-system
    labels:
      app: ebscsi
      tier: full
      category: system
    chart: aws-ebs-csi-driver/aws-ebs-csi-driver
    values:
    - ./overrides/aws-ebs-csi-driver.yaml.gotmpl

  - name: aws-ebs-csi-driver-secrets
    namespace: kube-system
    labels:
      app: ebscsi
      tier: secrets
      category: system
    chart: ./charts/secrets-injector
    values:
    - ./overrides/aws-ebs-csi-driver-secrets.yaml.gotmpl

  - name: prometheus
    namespace: monitoring
    labels:
      app: prometheus
      tier: full
      category: monitoring
    chart:  prometheus-community/prometheus
    version: 25.0.0

  - name: grafana
    namespace: monitoring
    labels:
      app: grafana
      tier: full
      category: monitoring
    chart: grafana/grafana
    version: 6.59.4
    values:
    - ./overrides/grafana/grafana.yaml.gotmpl
    - ./overrides/grafana/dashboards.yaml.gotmpl
