{{- if .Values.otlpIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otlp-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "signoz-telemetry.labels" . | nindent 4 }}
  {{- with .Values.otlpIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.otlpIngress.className }}
  rules:
    - host: {{ .Values.otlpIngress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signoz-otel-collector
                port:
                  number: 4318
  {{- if .Values.otlpIngress.tls }}
  tls:
    - hosts:
        - {{ .Values.otlpIngress.host }}
      secretName: {{ .Values.otlpIngress.tlsSecretName }}
  {{- end }}
{{- end }}
