storageClasses:
  - name: efs
    defaultClass: true
    annotations: {}
    provisioner: efs.csi.aws.com
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: false
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-changeme
      directoryPerms: "700"
    mountOptions: []
