apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: admin-targetgroup-secondary
  namespace: notification-canada-ca
spec:
  serviceRef:
    name: admin-secondary
    port: 6012
  targetGroupARN: arn:aws:elasticloadbalancing:ca-central-1:296255494825:targetgroup/admin-secondary/dbca992edd53ac7e
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: api-targetgroup-secondary
  namespace: notification-canada-ca
spec:
  serviceRef:
    name: api-secondary
    port: 6011
  targetGroupARN: arn:aws:elasticloadbalancing:ca-central-1:296255494825:targetgroup/k8s-api-secondary/a73736be8fb11789
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: documentation-targetgroup-secondary
  namespace: notification-canada-ca
spec:
  serviceRef:
    name: documentation-secondary
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ca-central-1:296255494825:targetgroup/document-secondary/c5846bbc8f3c72c6
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: dd-api-targetgroup-secondary
  namespace: notification-canada-ca
spec:
  serviceRef:
    name: document-download-api-secondary
    port: 7000
  targetGroupARN: arn:aws:elasticloadbalancing:ca-central-1:296255494825:targetgroup/doc-api-secondary/c2c171b0612d97c0