name: Update lambda function
description: Updates a lambda function, publishes a new version and updates the function alias
inputs:
  alias-name:
    description: Name of the alias to update
    required: true
  function-name:
    description: Name of the function to update
    required: true
  aws-region:
    description: AWS Region where the Lambda function and image are located
    default: ca-central-1
    required: false
  image-uri:
    description: Image tag to update the function with (if not specified, only the lambda description is updated to trigger a reload)
    default: ''
    required: false

runs:
  using: "composite"
  steps:
  
    - name: Update lambda image
      if: inputs.image-uri != ''
      shell: bash
      run: |
        aws lambda update-function-code \
          --region ${{ inputs.aws-region }} \
          --function-name ${{ inputs.function-name }} \
          --image-uri ${{ inputs.image-uri }}

    - name: Update lambda description
      if: inputs.image-uri == ''
      shell: bash
      run: |
        aws lambda update-function-configuration \
          --region ${{ inputs.aws-region }} \
          --function-name ${{ inputs.function-name }} \
          --description $(date -u +"%Y-%m-%dT%H:%M:%SZ")

    - name: Publish version and update alias
      shell: bash
      run: |
        aws lambda wait function-updated \
          --region ${{ inputs.aws-region }} \
          --function-name ${{ inputs.function-name }}
        VERSION="$(aws lambda publish-version \
          --region ${{ inputs.aws-region }} \
          --function-name ${{ inputs.function-name }} | jq -r '.Version')"

        aws lambda update-alias \
          --region ${{ inputs.aws-region }} \
          --function-name ${{ inputs.function-name }} \
          --name ${{ inputs.alias-name }} \
          --function-version "$VERSION"
