{{- if .Values.oneOffScriptJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jobs.fullname" . }}-one-off-{{ .Values.oneOffScriptJob.runId | trunc 20 | trimSuffix "-" }}
  labels:
    {{- include "jobs.labels" . | nindent 4 }}
    app: {{ include "jobs.name" . }}
    app.kubernetes.io/component: one-off-script
spec:
  backoffLimit: {{ .Values.oneOffScriptJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.oneOffScriptJob.ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ .Values.oneOffScriptJob.activeDeadlineSeconds }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "jobs.name" . }}
        app.kubernetes.io/component: one-off-script
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jobs.serviceAccountName" . }}
      restartPolicy: {{ .Values.oneOffScriptJob.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: one-off-script
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if gt (len .Values.oneOffScriptJob.command) 0 }}
          command:
            {{- toYaml .Values.oneOffScriptJob.command | nindent 12 }}
          {{- else if eq .Values.oneOffScriptJob.scriptType "python" }}
          command:
            - "poetry"
            - "run"
            - "python"
          {{- else }}
          command:
            - "/bin/sh"
          {{- end }}
          {{- if gt (len .Values.oneOffScriptJob.args) 0 }}
          args:
            {{- toYaml .Values.oneOffScriptJob.args | nindent 12 }}
          {{- else }}
          args:
            - {{ .Values.oneOffScriptJob.scriptPath | quote }}
          {{- end }}
          env:
            {{- range $key, $val := .Values.api }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $key, $val := .Values.apiSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretProviderClass.secretname }}
                  key: {{ $key }}
                  optional: {{ $.Values.oneOffScriptJob.secretKeyRefOptional }}
            {{- end }}
            {{- range $key, $val := .Values.oneOffScriptJob.extraEnv }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- if .Values.oneOffScriptJob.useInlineScript }}
          volumeMounts:
            - name: one-off-script
              mountPath: "/opt/one-off-script"
              readOnly: true
          {{- end }}
          {{- if .Values.secretProviderClass.enabled }}
          {{- if not .Values.oneOffScriptJob.useInlineScript }}
          volumeMounts:
          {{- end }}
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.oneOffScriptJob.resources | nindent 12 }}
      {{- if .Values.oneOffScriptJob.useInlineScript }}
      volumes:
        - name: one-off-script
          configMap:
            name: {{ include "jobs.fullname" . }}-one-off-script
            defaultMode: 0555
      {{- end }}
      {{- if .Values.secretProviderClass.enabled }}
      {{- if not .Values.oneOffScriptJob.useInlineScript }}
      volumes:
      {{- end }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "jobs.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
