{{- if and .Values.acme.enabled (gt (len .Values.acme.certificate.dnsNames) 0) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-default-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.acme.certificate.secretName }}
  issuerRef:
    name: {{ include "nginx-ingress.fullname" . }}-acme
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.acme.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
