{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    {{ .Values.secretProviderClass.parameters | toYaml | nindent 4 }}
  secretObjects:
    {{ .Values.secretProviderClass.secretObjects | toYaml | nindent 4 }}
{{- end }}
{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretname }}
    creationPolicy: Owner
    template:
      type: {{ .Values.externalSecret.secrettype }}
  data:
    {{- range $key, $val := .Values.externalSecret.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val }}
    {{- end }}
{{- end }}