{{- if .Values.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-acme
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.acme.email | quote }}
    server: {{ .Values.acme.server | quote }}
    privateKeySecretRef:
      name: {{ default (printf "%s-acme-account-key" (include "nginx-ingress.fullname" .)) .Values.acme.privateKeySecretName }}
    solvers:
      {{- if eq .Values.acme.solver "dns01" }}
      - dns01:
          route53:
            region: {{ .Values.acme.route53.region | quote }}
            {{- if .Values.acme.route53.hostedZoneID }}
            hostedZoneID: {{ .Values.acme.route53.hostedZoneID | quote }}
            {{- end }}
            {{- if .Values.acme.route53.role }}
            role: {{ .Values.acme.route53.role | quote }}
            {{- end }}
      {{- else }}
      - http01:
          ingress:
            ingressClassName: {{ .Values.controller.ingressClass.name }}
      {{- end }}
{{- end }}
