replicaCount: 2

image:
  repository: registry.k8s.io/sig-storage/snapshot-controller
  tag: v8.4.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi
