apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  flb_log_cw: "true"
  filters.conf: |
    [FILTER]
        Name parser
        Match *
        Key_name log
        Parser crio
        Reserve_Data On
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match kube.*
        region {{ .Values.region }}
        log_group_name /aws/eks/{{ .Values.clusterName }}/fargate
        log_stream_prefix {{ .Values.logStreamPrefix }}
        auto_create_group true
        log_key log
  parsers.conf: |
    [PARSER]
        Name crio
        Format Regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
