name: Dev - Helmfile Apply

on:
  push:
    branches:
      - main
    paths:
      - 'helmfile/overrides/dev.env'

env:
  ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ca-central-1

permissions:
  id-token: write # This is required for requesting the OIDC JWT
  contents: write # This is required for actions/checkout
  pull-requests: write

jobs:
  helmfile-apply:
    runs-on: ubuntu-latest
    steps:

      - name: Inject token authentication
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Configure credentials to Notify using OIDC
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{env.ACCOUNT_ID}}:role/notification-manifests-k8s-lambda-apply-main-branch
          role-session-name: NotifyManifestsApply
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0        

      - name: Read API Docker tag from dev.env
        run: |
          FILE=helmfile/overrides/dev.env
          if [ -f "$FILE" ]; then
            API_TAG=$(grep -E '^API_DOCKER_TAG:' "$FILE" | sed 's/API_DOCKER_TAG: *"\([^"]*\)".*/\1/' | tr -d '\r')
            echo "DEV_API_DOCKER_TAG=$API_TAG" >> $GITHUB_ENV
            echo "DEV_API_DOCKER_TAG: $API_TAG"
          else
            echo "Error: $FILE not found"
            exit 1
          fi

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@fd46979d2984c886929c416fbdf859b1c5efa0ea # v2.1.0
        with:
          install-kubectl: yes
          install-helm: yes        
          helmfile-version: "v1.4.4"
          helm-s3-plugin-version: "v0.16.2"

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1
        env: # In case you want to override default versions
          CONFTEST_VERSION: 0.30.0 
          TERRAFORM_VERSION: 1.9.5
          TERRAGRUNT_VERSION: 0.66.9
          TF_SUMMARIZE_VERSION: 0.2.3                    

      - name: Setup cluster access
        uses: ./.github/actions/setup-cluster-access
        with:
          environment: dev
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_DEV }}
          role-name: notification-manifests-k8s-lambda-apply-main-branch
          gha-vpn-id: ${{ secrets.GHA_VPN_ID_DEV }}
          gha-vpn-cert: ${{ secrets.GHA_VPN_CERT_DEV }}
          gha-vpn-key: ${{ secrets.GHA_VPN_KEY_DEV }}

      - name: Load Context Variables
        run: |
            ./helmfile/getContext.sh -g
             
      - name: Run Database Upgrade Helmfile Sync
        uses: ./.github/actions/db-migration
        with:
          environment: "dev"
          namespace: "notification-canada-ca"
          app_label: "notify-database"
          timeout: "400s"

      - name: Helmfile apply
        if: ${{ success() }}
        id: helmfile_apply
        run: |
          pushd helmfile
          helmfile --environment dev -l 'tier=crd' apply
          helmfile --environment dev -l 'app!=notify-database,tier!=crd' apply
          popd


