name: Staging - Helmfile Apply Individual
run-name: Staging - Helmfile Apply Individual ${{ github.event.inputs.app }} - ${{ github.event.inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Application to rollout'
        required: true
      selector:
        description: 'Selector for helmfile'
        required: true
      tag:
        description: 'Tag to rollout'
        default: 'latest'
        required: false
  repository_dispatch:
    types: [webhook]

permissions:
  id-token: write
  contents: read

jobs:
  rollout:
    runs-on: ubuntu-latest
    name: Rollout on EKS
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@fd46979d2984c886929c416fbdf859b1c5efa0ea # v2.1.0
        with:
          install-kubectl: yes
          install-helm: yes
          helmfile-version: "v1.4.4"
          helm-s3-plugin-version: "v0.16.2"

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1
        env: # In case you want to override default versions
          CONFTEST_VERSION: 0.30.0 
          TERRAFORM_VERSION: 1.9.5
          TERRAGRUNT_VERSION: 0.66.9
          TF_SUMMARIZE_VERSION: 0.2.3                                  

      - name: Setup cluster access
        uses: ./.github/actions/setup-cluster-access
        with:
          environment: staging
          aws-account-id: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_STAGING }}
          role-name: notification-manifests-helmfile-staging-apply
          gha-vpn-id: ${{ secrets.GHA_VPN_ID_STAGING }}
          gha-vpn-cert: ${{ secrets.GHA_VPN_CERT_STAGING }}
          gha-vpn-key: ${{ secrets.GHA_VPN_KEY_STAGING }}

      - name: Load EnvVars
        run: |
            ./helmfile/getContext.sh -g

      - name: Run helmfile
        id: helmfile_apply
        run: |
          pushd helmfile
          helmfile --environment staging -l ${{ github.event.inputs.selector }} apply
          popd

      - name: Notify Slack channel if this job failed
        if: ${{ failure() }}
        run: |
          json='{"text":"<!here> Staging - ${{ github.event.inputs.app }} - ${{ github.event.inputs.tag }} Kubernetes Rollout is failing in <https://github.com/cds-snc/notification-manifests/actions/runs/'${{ github.run_id }}'|notification-manifests> !"}'
          curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_WEBHOOK }}
