name: Test - Velero Snapshot Reusable Call (Staging)

on:
  push:
    branches:
      - switch-to-gha-vpn-secrets

permissions:
  id-token: write
  contents: read

jobs:
  pre-apply-snapshot:
    uses: ./.github/workflows/velero_snapshot.yaml
    with:
      environment: staging
    secrets: inherit
