name: Test Commit Verified Action

on:
  push:
    branches:
      - gh-bot-commit-signing

jobs:
  test-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Obtain a Notify PR Bot GitHub App Installation Access Token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token@1.1.0 ci ${{ secrets.PR_BOT_GITHUB_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "GITHUB_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Make a dummy change
        run: |
          echo "Last run: $(date)" > dummy-test-file.txt

      - name: Commit using the action
        uses: ./.github/actions/commit-verified
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          commit-message: "chore(test): dummy commit to verify signing API [skip ci]"
          files: dummy-test-file.txt